/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qltv;
/**
 *
 * @author Nanoeagle
 */
public class AccountGUI extends javax.swing.JFrame {

    /**
     * Creates new form AccountGUI
     */
    public AccountGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        account_Panel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        logout_btn = new javax.swing.JButton();
        bookSearch_btn = new javax.swing.JButton();
        readerSearch_btn = new javax.swing.JButton();
        readerRegistration_btn = new javax.swing.JButton();
        seeLoanHistory_btn = new javax.swing.JButton();
        addBook_btn = new javax.swing.JButton();
        handleBorrowingBook_btn = new javax.swing.JButton();
        handleReturningBook_btn = new javax.swing.JButton();
        exportReport_btn = new javax.swing.JButton();
        main_Panel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(850, 520));
        setResizable(false);

        account_Panel.setBackground(new java.awt.Color(32, 30, 103));
        account_Panel.setPreferredSize(new java.awt.Dimension(150, 520));
        account_Panel.setRequestFocusEnabled(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("TVKHTH");

        logout_btn.setBackground(new java.awt.Color(32, 30, 103));
        logout_btn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        logout_btn.setForeground(new java.awt.Color(255, 255, 255));
        logout_btn.setText("Đăng xuất");
        logout_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logout_btnActionPerformed(evt);
            }
        });

        bookSearch_btn.setBackground(new java.awt.Color(32, 30, 103));
        bookSearch_btn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        bookSearch_btn.setForeground(new java.awt.Color(255, 255, 255));
        bookSearch_btn.setText("Tra cứu sách");
        bookSearch_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookSearch_btnActionPerformed(evt);
            }
        });

        readerSearch_btn.setBackground(new java.awt.Color(32, 30, 103));
        readerSearch_btn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        readerSearch_btn.setForeground(new java.awt.Color(255, 255, 255));
        readerSearch_btn.setText("Tra cứu bạn đọc");
        readerSearch_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readerSearch_btnActionPerformed(evt);
            }
        });

        readerRegistration_btn.setBackground(new java.awt.Color(32, 30, 103));
        readerRegistration_btn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        readerRegistration_btn.setForeground(new java.awt.Color(255, 255, 255));
        readerRegistration_btn.setText("Đăng ký bạn đọc");
        readerRegistration_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readerRegistration_btnActionPerformed(evt);
            }
        });

        seeLoanHistory_btn.setBackground(new java.awt.Color(32, 30, 103));
        seeLoanHistory_btn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        seeLoanHistory_btn.setForeground(new java.awt.Color(255, 255, 255));
        seeLoanHistory_btn.setText("Lịch sử mượn trả");
        seeLoanHistory_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeLoanHistory_btnActionPerformed(evt);
            }
        });

        addBook_btn.setBackground(new java.awt.Color(32, 30, 103));
        addBook_btn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        addBook_btn.setForeground(new java.awt.Color(255, 255, 255));
        addBook_btn.setText("Thêm sách");
        addBook_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBook_btnActionPerformed(evt);
            }
        });

        handleBorrowingBook_btn.setBackground(new java.awt.Color(32, 30, 103));
        handleBorrowingBook_btn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        handleBorrowingBook_btn.setForeground(new java.awt.Color(255, 255, 255));
        handleBorrowingBook_btn.setText("Xử lý mượn");
        handleBorrowingBook_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleBorrowingBook_btnActionPerformed(evt);
            }
        });

        handleReturningBook_btn.setBackground(new java.awt.Color(32, 30, 103));
        handleReturningBook_btn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        handleReturningBook_btn.setForeground(new java.awt.Color(255, 255, 255));
        handleReturningBook_btn.setText("Xử lý trả");
        handleReturningBook_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleReturningBook_btnActionPerformed(evt);
            }
        });

        exportReport_btn.setBackground(new java.awt.Color(32, 30, 103));
        exportReport_btn.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        exportReport_btn.setForeground(new java.awt.Color(255, 255, 255));
        exportReport_btn.setText("Báo cáo thống kê");
        exportReport_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exportReport_btnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout account_PanelLayout = new javax.swing.GroupLayout(account_Panel);
        account_Panel.setLayout(account_PanelLayout);
        account_PanelLayout.setHorizontalGroup(
            account_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(account_PanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(account_PanelLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(logout_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(bookSearch_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(readerSearch_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(readerRegistration_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(seeLoanHistory_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(addBook_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(handleBorrowingBook_btn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(handleReturningBook_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(exportReport_btn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
        );
        account_PanelLayout.setVerticalGroup(
            account_PanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(account_PanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addComponent(logout_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bookSearch_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(readerSearch_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(seeLoanHistory_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addBook_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(readerRegistration_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(handleBorrowingBook_btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(handleReturningBook_btn)
                .addGap(11, 11, 11)
                .addComponent(exportReport_btn)
                .addContainerGap(111, Short.MAX_VALUE))
        );

        main_Panel.setBackground(new java.awt.Color(255, 255, 255));
        main_Panel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(account_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(main_Panel, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(account_Panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(main_Panel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logout_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logout_btnActionPerformed
        if (Helper.isContinued(main_Panel)) {
            new LoginGUI().setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_logout_btnActionPerformed

    private void bookSearch_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookSearch_btnActionPerformed
        main_Panel.removeAll();
        main_Panel.add(new BookSearchGUI());
        main_Panel.repaint();
        main_Panel.revalidate();
    }//GEN-LAST:event_bookSearch_btnActionPerformed

    private void readerSearch_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readerSearch_btnActionPerformed
        main_Panel.removeAll();
        main_Panel.add(new ReaderSearchGUI());
        main_Panel.repaint();
        main_Panel.revalidate();
    }//GEN-LAST:event_readerSearch_btnActionPerformed

    private void readerRegistration_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readerRegistration_btnActionPerformed
        main_Panel.removeAll();
        main_Panel.add(new ReaderRegistrationGUI());
        main_Panel.repaint();
        main_Panel.revalidate();
    }//GEN-LAST:event_readerRegistration_btnActionPerformed

    private void seeLoanHistory_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeLoanHistory_btnActionPerformed
        main_Panel.removeAll();
        main_Panel.add(new LoanHistoryGUI());
        main_Panel.repaint();
        main_Panel.revalidate();
    }//GEN-LAST:event_seeLoanHistory_btnActionPerformed

    private void addBook_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBook_btnActionPerformed
        main_Panel.removeAll();
        main_Panel.add(new BookAddingGUI());
        main_Panel.repaint();
        main_Panel.revalidate();
    }//GEN-LAST:event_addBook_btnActionPerformed

    private void handleBorrowingBook_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleBorrowingBook_btnActionPerformed
        main_Panel.removeAll();
        main_Panel.add(new BorrowHandlingGUI());
        main_Panel.repaint();
        main_Panel.revalidate();
    }//GEN-LAST:event_handleBorrowingBook_btnActionPerformed

    private void handleReturningBook_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleReturningBook_btnActionPerformed
        main_Panel.removeAll();
        main_Panel.add(new ReturnHandlingGUI());
        main_Panel.repaint();
        main_Panel.revalidate();
    }//GEN-LAST:event_handleReturningBook_btnActionPerformed

    private void exportReport_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exportReport_btnActionPerformed
        main_Panel.removeAll();
        main_Panel.add(new NotAllowedGUI());
        main_Panel.repaint();
        main_Panel.revalidate();
    }//GEN-LAST:event_exportReport_btnActionPerformed
  
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JPanel account_Panel;
    javax.swing.JButton addBook_btn;
    javax.swing.JButton bookSearch_btn;
    javax.swing.JButton exportReport_btn;
    javax.swing.JButton handleBorrowingBook_btn;
    javax.swing.JButton handleReturningBook_btn;
    javax.swing.JLabel jLabel1;
    javax.swing.JSeparator jSeparator1;
    javax.swing.JButton logout_btn;
    javax.swing.JPanel main_Panel;
    javax.swing.JButton readerRegistration_btn;
    javax.swing.JButton readerSearch_btn;
    javax.swing.JButton seeLoanHistory_btn;
    // End of variables declaration//GEN-END:variables
}
