/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qltv;

import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.JComponent;

/**
 *
 * @author Nanoeagle
 */
public class BorrowHandlingGUI extends javax.swing.JPanel {

    /**
     * Creates new form BookSearchGUI
     */
    public BorrowHandlingGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        readerBoHaSearch_TxField = new javax.swing.JTextField();
        addBrwHdling_btn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        brwHdlingTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bookBoHaSearch_TxField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        handleBorrowing_btn = new javax.swing.JButton();
        borrowFee_label = new javax.swing.JLabel();
        errorBook = new javax.swing.JLabel();
        errorReader = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setToolTipText("");
        setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 520));

        readerBoHaSearch_TxField.setPreferredSize(new java.awt.Dimension(400, 30));
        readerBoHaSearch_TxField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readerBoHaSearch_TxFieldActionPerformed(evt);
            }
        });

        addBrwHdling_btn.setText("Thêm sách");
        addBrwHdling_btn.setPreferredSize(new java.awt.Dimension(60, 30));
        addBrwHdling_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBrwHdling_btnActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);
        
        brwHdlingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã cuốn sách", "Tựa sách", "Tác giả", "Giá bìa", "Xóa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(brwHdlingTable);
        
        brwHdlingTable.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                rowSelectionMouseClicked(e);
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {}
            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {}
            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {}
            @Override
            public void mouseReleased(java.awt.event.MouseEvent e) {}
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Nhập mã bạn đọc");

        bookBoHaSearch_TxField1.setPreferredSize(new java.awt.Dimension(400, 30));
        bookBoHaSearch_TxField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookBoHaSearch_TxField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Nhập mã cuốn sách");

        handleBorrowing_btn.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        handleBorrowing_btn.setText("Mượn");
        handleBorrowing_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleBorrowing_btnActionPerformed(evt);
            }
        });
        
        borrowFee_label.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        borrowFee_label.setText("Tổng phí:");

        errorBook.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        errorReader.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        compos = new ArrayList<>();
        compos.add(readerBoHaSearch_TxField);
        compos.add(bookBoHaSearch_TxField1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(402, 402, 402)
                        .addComponent(borrowFee_label)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(handleBorrowing_btn)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(readerBoHaSearch_TxField, javax.swing.GroupLayout.DEFAULT_SIZE, 206, Short.MAX_VALUE)
                    .addComponent(jLabel1)
                    .addComponent(errorReader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(errorBook, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(bookBoHaSearch_TxField1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addBrwHdling_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(readerBoHaSearch_TxField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addBrwHdling_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookBoHaSearch_TxField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorBook)
                    .addComponent(errorReader))
                .addGap(10, 10, 10)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(borrowFee_label)
                    .addComponent(handleBorrowing_btn))
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addBrwHdling_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBrwHdling_btnActionPerformed
        BorrowHandlingCtrl.handleAddBtn(this);
    }//GEN-LAST:event_addBrwHdling_btnActionPerformed

    private void readerBoHaSearch_TxFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readerBoHaSearch_TxFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readerBoHaSearch_TxFieldActionPerformed

    private void bookBoHaSearch_TxField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookBoHaSearch_TxField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookBoHaSearch_TxField1ActionPerformed

    private void handleBorrowing_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleBorrowing_btnActionPerformed
        BorrowHandlingCtrl.handleBorrowBtn(this);
    }//GEN-LAST:event_handleBorrowing_btnActionPerformed

    void rowSelectionMouseClicked(MouseEvent e) {
        BorrowHandlingCtrl.handleRowSelection(this);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton addBrwHdling_btn;
    javax.swing.JTextField bookBoHaSearch_TxField1;
    javax.swing.JLabel borrowFee_label;
    javax.swing.JTable brwHdlingTable;
    javax.swing.JLabel errorBook;
    javax.swing.JLabel errorReader;
    javax.swing.JButton handleBorrowing_btn;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JScrollPane jScrollPane3;
    javax.swing.JTextField readerBoHaSearch_TxField;

    ArrayList<JComponent> compos;
    // End of variables declaration//GEN-END:variables
}
