/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package qltv;

import java.awt.event.*;
import java.util.ArrayList;
import javax.swing.JComponent;
/**
 *
 * @author Nanoeagle
 */
public class ReturnHandlingGUI extends javax.swing.JPanel {

    /**
     * Creates new form BookSearchGUI
     */
    public ReturnHandlingGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        readerID_TxField = new javax.swing.JTextField();
        addRtnHdling_btn = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        rtnHdlingTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        bookRtnSearch_TxField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        handleReturning_btn = new javax.swing.JButton();
        returnFee_label = new javax.swing.JLabel();
        createDept_btn = new javax.swing.JButton();
        errorReader = new javax.swing.JLabel();
        errorBook = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setToolTipText("");
        setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        setPreferredSize(new java.awt.Dimension(700, 520));

        readerID_TxField.setEditable(false);
        readerID_TxField.setPreferredSize(new java.awt.Dimension(400, 30));
        readerID_TxField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readerID_TxFieldActionPerformed(evt);
            }
        });

        addRtnHdling_btn.setText("Thêm sách");
        addRtnHdling_btn.setPreferredSize(new java.awt.Dimension(60, 30));
        addRtnHdling_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addRtnHdling_btnActionPerformed(evt);
            }
        });

        jScrollPane3.setBackground(new java.awt.Color(255, 255, 255));
        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        rtnHdlingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã cuốn sách", "Tựa sách", "Tác giả", "Giá bìa", "Xóa"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(rtnHdlingTable);

        rtnHdlingTable.addMouseListener(new MouseListener() {
            @Override
            public void mouseClicked(MouseEvent e) {
                rowSelectionmMouseClicked(e);
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {}
            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {}
            @Override
            public void mousePressed(java.awt.event.MouseEvent e) {}
            @Override
            public void mouseReleased(java.awt.event.MouseEvent e) {}
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Mã bạn đọc");

        bookRtnSearch_TxField1.setPreferredSize(new java.awt.Dimension(400, 30));
        bookRtnSearch_TxField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookRtnSearch_TxField1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Nhập mã cuốn sách");

        handleReturning_btn.setText("Trả");
        handleReturning_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                handleReturning_btnActionPerformed(evt);
            }
        });

        returnFee_label.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        returnFee_label.setText("Tổng phí:");

        createDept_btn.setText("Tạo nợ");
        createDept_btn.setPreferredSize(new java.awt.Dimension(65, 25));
        createDept_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDept_btnActionPerformed(evt);
            }
        });

        errorReader.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        errorBook.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N

        compos = new ArrayList<>();
        compos.add(readerID_TxField);
        compos.add(bookRtnSearch_TxField1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(returnFee_label)
                        .addGap(202, 202, 202)
                        .addComponent(createDept_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(handleReturning_btn)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(readerID_TxField, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(errorReader))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(bookRtnSearch_TxField1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addRtnHdling_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel2)
                    .addComponent(errorBook))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(readerID_TxField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addRtnHdling_btn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bookRtnSearch_TxField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(errorReader)
                    .addComponent(errorBook))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(returnFee_label)
                    .addComponent(handleReturning_btn)
                    .addComponent(createDept_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(87, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addRtnHdling_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addRtnHdling_btnActionPerformed
        ReturnHandlingCtrl.handleAddBtn(this);
    }//GEN-LAST:event_addRtnHdling_btnActionPerformed

    private void bookRtnSearch_TxField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookRtnSearch_TxField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bookRtnSearch_TxField1ActionPerformed

    private void handleReturning_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_handleReturning_btnActionPerformed
        ReturnHandlingCtrl.handleReturnBtn(this);
    }//GEN-LAST:event_handleReturning_btnActionPerformed

    private void readerID_TxFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readerID_TxFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_readerID_TxFieldActionPerformed

    private void createDept_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDept_btnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createDept_btnActionPerformed

    void rowSelectionmMouseClicked(MouseEvent e) {
        ReturnHandlingCtrl.handleRowSelection(this);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton addRtnHdling_btn;
    javax.swing.JTextField bookRtnSearch_TxField1;
    javax.swing.JButton createDept_btn;
    javax.swing.JLabel errorBook;
    javax.swing.JLabel errorReader;
    javax.swing.JButton handleReturning_btn;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JScrollPane jScrollPane3;
    javax.swing.JTextField readerID_TxField;
    javax.swing.JLabel returnFee_label;
    javax.swing.JTable rtnHdlingTable;

    ArrayList<JComponent> compos;
    // End of variables declaration//GEN-END:variables
}
